ALTER TABLE messages ADD COLUMN IF NOT EXISTS file_url TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS file_name VARCHAR(300) NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS file_mime VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS file_size INTEGER NOT NULL DEFAULT 0;
