ALTER TABLE t_p60921926_iconfood_project_man.users
  ADD COLUMN IF NOT EXISTS tg_chat_id VARCHAR(40) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tg_code VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tg_username VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tg_channel_id INTEGER NOT NULL DEFAULT 0;

ALTER TABLE t_p60921926_iconfood_project_man.messages
  ADD COLUMN IF NOT EXISTS via VARCHAR(20) NOT NULL DEFAULT '';