ALTER TABLE t_p60921926_iconfood_project_man.users
  ADD COLUMN IF NOT EXISTS max_user_id VARCHAR(40) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS max_code VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS max_username VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS max_channel_id INTEGER NOT NULL DEFAULT 0;