ALTER TABLE push_subscriptions
    ADD COLUMN IF NOT EXISTS on_task BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS on_deadline BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS on_comment BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS on_chat BOOLEAN NOT NULL DEFAULT FALSE;
